### ISSUE TITLE
Flaws

### ISSUE THREAD

**Issue by NeonWizard** [gunslinger23/scp-sl-whitelist#1]
What's stopping the UDP flood attackers from targeting this application and populating it with IP addresses before sending the packets?

What about users with a dynamic IP address?

**Comment by gunslinger23** [comment]
You can look at the `start.sh`, it use iptables to allow udp packet input from whitelist source.
The golang program is a web server to setting the whitelist ipset.

**It only protect the specific port which set in iptables (7777)**

It's not friendly to dynamic IP user, but must of the user's IP won't change so fast.

**Comment by gunslinger23** [comment]
It just a easy tool to protect some simple way of attack.
